Added German translation
TheThingsNetwork/Manifest pull request #13
Opened 2019-03-10 18:53 UTC by lanmarc77

How about adding a German translation?

2019-03-10 18:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/TheThingsNetwork/Manifest?pullRequest=13) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/TheThingsNetwork/Manifest?pullRequest=13) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/TheThingsNetwork/Manifest?pullRequest=13) it.</sub>

2019-03-11 10:51 UTC, johanstokking commented
@lanmarc77 thanks! Our native speaker @kschiffer will review!

2019-03-13 10:00 UTC, kschiffer requested changes
Hey @lanmarc77, thanks a lot for your contribution of a German translation! I have added some suggested changes, which I think will improve readability, fix a couple of typos and other issues. If you agree, you can integrate those and we can merge the PR.

2019-03-13 10:00 UTC, kschiffer commented on Mission.de.md
> +Menschen, die damals ihre Netzwerke geöffnet und Datenaustausch über diese Netze zuließen, haben das Internet erschaffen. Dadurch entstand eine Synergie, die ein Wachstum ermöglichte, welches zu etwa
```suggestion
Menschen, die damals ihre Netzwerke geöffnet und Datenaustausch über diese Netze zuließen, haben das Internet erschaffen. Dadurch entstand eine Synergie, die eine Entwicklung lostrat, die heute mehr ist, als die Summe seiner Teile.
```

2019-03-13 10:00 UTC, kschiffer commented on Mission.de.md
> +Das The Things Network will zukünftig das gleiche mit dem IoT Netzwerk versuchen.
```suggestion
Im selben Geiste möchte _The Things Network_ ein weltweites, offenes IoT Netzwerk ermöglichen.
```

2019-03-13 10:00 UTC, kschiffer commented on Mission.de.md
> +Dem Ansatz von Moore‘s Gesetz folgend, verringern sich die Kosten von Computerkomponenten exponentiell. Die neue Generation von Netzwerkgeräten haben einen Preissegment erreicht, welches eine Finanzi
```suggestion
Dem Ansatz von Moore‘s Gesetz folgend, verringern sich die Kosten von Computerkomponenten exponentiell. Die neue Generation von Netzwerkgeräten haben einen Preissegment erreicht, welches eine Finanzierung eines Community-basierten Netzwerkes durch ermöglicht.
```

2019-03-13 10:00 UTC, kschiffer commented on Mission.de.md
> +Aktuelle Technologien machen es nun möglich ein kostengünstiges Datennetzwerk zu schaffen, welches durch eine freie Gemeinschaft der Nutzer bereitgestellt wird. Für ein Land wie beispielsweise die Ni
```suggestion
Aktuelle Technologien machen es nun möglich, ein kostengünstiges Datennetzwerk zu schaffen, welches durch eine freie und offene Community bereitgestellt wird. Für ein Land wie beispielsweise die Niederlande, benötigt man weniger als 80 Gateways für eine flächendeckende Versorgung. Eine Stadt wie Amsterdam benötigt dafür nur 5 Gateways. Bei Kosten für ein Gateway, die mit denen eines durchschnittlichen Laptops vergleichbar sind, ist dies ein gut erreichbares Ziel.
```

2019-03-13 10:00 UTC, kschiffer commented on Mission.de.md
> +Jeder sollte in der Lage sein, Sensorendaten entweder zu versenden oder online abrufen zu können. Keine Monopole oder beschränkter Marktzugang sollte hier möglich sein.
```suggestion
Jeder sollte in der Lage sein, Sensorendaten entweder zu versenden oder online abrufen zu können. Diese Freiheit sollte durch keine privaten oder staatlichen Monopole beschränkt werden.
```

2019-03-13 10:00 UTC, kschiffer commented on Mission.de.md
> +Unsere Mission ist der Aufbau eines dezentralen, Technologie unabhängigen IoT Netzwerkes, welches durch die Gemeinschaft der Nutzer betrieben wird und deren Eigentum ist.
```suggestion
Unsere Mission ist der Aufbau eines dezentralen, Technologieunabhängigen IoT Netzwerkes, welches durch die Gemeinschaft der Nutzer betrieben wird und deren Eigentum ist.
```

2019-03-13 10:00 UTC, kschiffer commented on Mission.de.md
> +Wir erschaffen ein verteiltes Netzwerk, welches jegliche Formen der IoT Verbindungen unterstützt. Ein Netzwerk, welches von Beginn an demokratisch aufgebaut ist. Wir wollen sicherstellen, dass keine
```suggestion
Wir erschaffen ein verteiltes Netzwerk, welches jegliche Formen der IoT Verbindungen unterstützt. Ein Netzwerk, welches von Beginn an demokratisch aufgebaut ist. Wir wollen sicherstellen, dass kein einzelner Akteur IoT dominieren kann. Deshalb achten wir auf Netzneutralität und stellen eine Basis von verteilten Installationen von Gateways bereit, welche über ein Netzwerk zum Datenaustausch verbunden sind.
```

2019-03-13 10:00 UTC, kschiffer commented on Mission.de.md
> +Das Fundament dieses Netzwerkes sind die folgenden Prinzipien:
```suggestion
Das Fundament des _The Things Network_ sind die folgenden Prinzipien:
```

2019-03-13 10:00 UTC, kschiffer commented on Mission.de.md
> +Das The Things Network wurde in Amsterdam gestartet. Wir haben bereits Partner gefunden, die ein Netzwerk errichten, welches die ganze Stadt abdeckt. Weitere Partner gründen auf dieser Basis Startups
```suggestion
Das _The Things Network_ wurde in Amsterdam gestartet. Wir haben bereits Partner gefunden, die ein Netzwerk errichten, welches die ganze Stadt abdeckt. Weitere Partner gründen auf dieser Basis Startups. Wir versuchen ein Weg aufzuzeigen, der als Blaupause für den Rest der Welt dienen kann.
```

2019-03-13 10:00 UTC, kschiffer commented on Mission.de.md
> +Das Ziel unserer Gemeinschaft ist es, ein weltweit dezentrales Internet of Things Internet zu erschaffen.
```suggestion
Das Ziel unserer Community ist es, ein weltweites, dezentrales Internet of Things Internet zu erschaffen. 
```

2019-03-13 10:00 UTC, kschiffer commented on README.de.md
> +Diejenigen, die dieses Netzwerk kontrollieren, werden die Welt kontrollieren. *__Wir glauben, dass eine solche Macht nicht auf wenige Personen, Firmen oder Nationen verteilt sein sollte. Wir glauben
```suggestion
Diejenigen, die dieses Netzwerk kontrollieren, werden die Welt kontrollieren. *__Wir glauben, dass eine solche Macht nicht auf wenige Personen, Firmen oder Nationen konzentriert sein sollte. Wir glauben, dass eine solche Macht an so viele Personen wie möglich verteilt werden muss.__* Um das zu erreichen, haben wir das „The Things Network“ gegründet.
```

2019-03-13 10:00 UTC, kschiffer commented on README.de.md
> +* Der erste Teil einer solchen Verbindung findet drahtlos („Over The Air“) statt, der zweite Teil in einem Computernetzwerk („Over The Net“). Die dafür notwendigen Systeme, Konzepte und deren Aufbau
```suggestion
* Der erste Teil einer solchen Verbindung findet drahtlos („Over The Air“) statt, der zweite Teil in einem Computernetzwerk („Over The Net“). Die dafür notwendigen Systeme, Konzepte und deren Aufbau nennen sich „The Things Network“.
```

2019-03-13 10:00 UTC, kschiffer commented on README.de.md
> +* Jeder ist frei eigene „Things“ zu betreiben und diese mit einem „Things Gateway“  zu verbinden, unabhängig von dessen Eigentumsverhältnis.
```suggestion
* Jeder ist frei, eigene „Things“ zu betreiben und diese mit einem „Things Gateway“  zu verbinden, unabhängig von seinen/ihren finanziellen Möglichkeiten.
```

2019-03-13 10:00 UTC, kschiffer commented on README.de.md
> +* Jeder ist frei eigene „Things Gateways“ zu betreiben und diese mit einem „Things Access“ zu verbinden, unabhängig von dessen Eigentumsverhältnis. Diese „Things Gateways“ geben Zugriff zu allen „Thi
```suggestion
* Jeder ist frei eigene „Things Gateways“ zu betreiben und diese mit einem „Things Access“ zu verbinden, unabhängig von dessen finanziellen Möglichkeiten. Diese „Things Gateways“ geben Zugriff zu allen „Things“ mit einem Ansatz der Netzneutralität, lediglich limitiert durch die zur Verfügung stehende Bandbreite.
```

2019-03-13 10:00 UTC, kschiffer commented on README.de.md
> +* Jeder ist frei einen eigenen „Things Access“ zu betreiben und anonyme Verbindungen über das Internet bereitzustellen. Dieses „Things Access“ erlaubt Zugriff auf alle „Things Gateways“ mit einem Ans
```suggestion
* Jeder ist frei einen eigenen „Things Access“ zu betreiben und anonyme Verbindungen über das Internet bereitzustellen. Dieses „Things Access“ erlaubt Zugriff auf alle „Things Gateways“ mit einem Ansatz der Netzneutralität, lediglich limitiert durch die zur Verfügung stehende Bandbreite. Dieses „Things Access“ erlaubt auch die Verbindung mit anderen „Things Access“, um Daten auszutauschen.
```

2019-03-13 10:00 UTC, kschiffer commented on README.de.md
> +* Jeder der das „The Things Network“ benutzt, darf dies für beliebige Zwecke tun, beschränkt lediglich durch lokale Rechtsvorschriften, auf eigenes Risiko und mit dem Wissen, dass die Bereitstellung
```suggestion
* Jeder der das „The Things Network“ benutzt, darf dies für beliebige Zwecke tun, beschränkt lediglich durch die jeweils gültigen lokalen Rechtsvorschriften, auf eigenes Risiko und mit dem Wissen, dass die Bereitstellung ohne Gewährleistung erfolgt und jederzeit ohne Ankündigung und ohne Angabe von Gründen beendet werden kann. Produkte und Services, die sich aus der Nutzung ableiten, dürfen Sie frei für jeden anbieten, kommerzielle Zielen verfolgen, nur bestimmten Personen zur Verfügung stellen, ohne Gewinnerzielungsabsicht oder mit jeder anderen Absicht anbieten. Anbieter des „The Things Network“ erlegen ihren Nutzern keine Beschränkungen auf.
```

2019-03-13 10:00 UTC, kschiffer commented on Mission.de.md
> +Das The Things Network ist ein offenes, dezentrales und "crowd sourced" Internet of Things (IoT) Datennetzwerk.
```suggestion
Das _The Things Network_ ist ein offenes, dezentrales und "crowd sourced" Internet of Things (IoT) Datennetzwerk.
```

2019-03-14 12:25 UTC, johanstokking commented
Awesome, is this ready?

2019-03-14 12:28 UTC, kschiffer approved these changes

2019-03-14 14:51 UTC, merged

2019-03-14 14:51 UTC, johanstokking commented
Thanks @lanmarc77